// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Capabilities = { webgpu: boolean; vulkan: boolean; cuda: boolean; rocm: boolean; directml: boolean; mps: boolean; openvino: boolean }

export type CpuInfo = { model: string; cores: number; speedMHz: number }

export type GpuInfo = { name: string; vendor: Vendor; architecture?: string | null; driverVersion: string; temperature: number; gpuPercent: number; gfxVersion?: string | null; vram: VramInfo; capabilities: Capabilities; hsaOverrideGfx?: string | null; vulkanHeaps?: VulkanHeaps | null; opProbes?: OpProbes | null }

export type MemoryInfo = { total: string; free: string; processHeapUsed: string }

export type OpProbes = { torch_conv1d?: ProbeResult | null }

export type OrtBackend = { name: string; bundled: boolean }

export type OrtInfo = { version: string; backends: OrtBackend[] }

export type PlatformInfo = { os: string; arch: string; release: string; hostname: string; runtime: string; runtimeVersion: string; nodeVersion?: string | null }

export type ProbeResult = "ok" | "fail"

export type ProceduresLegacy = { queries: { key: "checkTorch"; input: null; result: boolean } | { key: "deviceInfo"; input: null; result: { platform: PlatformInfo; cpu: CpuInfo; memory: MemoryInfo; gpu: GpuInfo[]; ort: OrtInfo } } | { key: "getGroupList"; input: null; result: ({ group_id: string; task_count: number; created_at: string | null; tasks: TaskBrief[] })[] } | { key: "readInput"; input: null; result: string } | { key: "readInputSchema"; input: null; result: string } | { key: "version"; input: null; result: string }; mutations: { key: "startTorch"; input: null; result: number } | { key: "startVoxcpm"; input: null; result: number } | { key: "stopTorch"; input: null; result: null } | { key: "stopVoxcpm"; input: null; result: null } | { key: "writeInput"; input: string; result: null }; subscriptions: never }

export type TaskBrief = { id: string; title: string | null; status: string; current_stage: string | null; created_at: string; started_at: string | null; completed_at: string | null }

export type Vendor = "amd" | "nvidia" | "intel" | "unknown"

export type VramInfo = { percent: number; total?: number | null; used?: number | null; type?: VramType | null; reserved?: number | null; gtt?: number | null }

export type VramType = "dedicated" | "shared" | "unknown"

export type VulkanHeaps = { deviceLocal: number; hostVisible: number }

export type Procedures = {
	checkTorch: { kind: "query", input: null, output: boolean, error: unknown },
	deviceInfo: { kind: "query", input: null, output: { platform: PlatformInfo; cpu: CpuInfo; memory: MemoryInfo; gpu: GpuInfo[]; ort: OrtInfo }, error: unknown },
	getGroupList: { kind: "query", input: null, output: ({ group_id: string; task_count: number; created_at: string | null; tasks: TaskBrief[] })[], error: unknown },
	readInput: { kind: "query", input: null, output: string, error: unknown },
	readInputSchema: { kind: "query", input: null, output: string, error: unknown },
	startTorch: { kind: "mutation", input: null, output: number, error: unknown },
	startVoxcpm: { kind: "mutation", input: null, output: number, error: unknown },
	stopTorch: { kind: "mutation", input: null, output: null, error: unknown },
	stopVoxcpm: { kind: "mutation", input: null, output: null, error: unknown },
	version: { kind: "query", input: null, output: string, error: unknown },
	writeInput: { kind: "mutation", input: string, output: null, error: unknown },
}