// Auto-generated by fnrpc. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
export type AsrRunInfo = {
	engine: string,
	device: string,
	compute_type: string | null,
	gpu_attempted: boolean | null,
	fallback_to_cpu: boolean | null,
};

export type Capabilities = {
	webgpu: boolean,
	vulkan: boolean,
	cuda: boolean,
	rocm: boolean,
	directml: boolean,
	mps: boolean,
	openvino: boolean,
};

export type Context = {
	task: Task,
	stages: TaskStage[] | null,
	pipeline: string,
	last_run_pipeline: string | null,
	input: unknown,
	run_info: RunInfo | null,
	video_source_path: string | null,
	audio_source_path: string | null,
	asr_language: string | null,
	target_language: string | null,
};

export type CpuInfo = {
	model: string,
	cores: number,
	speed_mhz: number | null,
};

export type DeviceInfo = {
	platform: PlatformInfo,
	cpu: CpuInfo,
	memory: MemoryInfo,
	gpu: GpuInfo[],
	ort: OrtInfo,
};

export type DirEntry = {
	name: string,
	is_dir: boolean,
	size: bigint | null,
};

export type FoundVia = "Mdns" | "Default" | "PortFile";

export type GpuInfo = {
	name: string,
	vendor: Vendor,
	architecture: string | null,
	driver_version: string,
	temperature: number | null,
	gpu_percent: number | null,
	gfx_version: string | null,
	vram: VramInfo,
	capabilities: Capabilities,
	hsa_override_gfx: string | null,
	vulkan_heaps: VulkanHeaps | null,
	op_probes: OpProbes | null,
};

export type GroupInfo = {
	group_id: string,
	task_count: number,
	created_at: string | null,
	tasks: TaskBrief[],
};

export type MemoryInfo = {
	total: string,
	free: string,
	process_heap_used: string,
};

export type OpProbes = {
	torch_conv1d: ProbeResult | null,
};

export type OrtBackend = {
	name: string,
	bundled: boolean,
};

export type OrtInfo = {
	version: string,
	backends: OrtBackend[],
};

export type PlatformInfo = {
	os: string,
	arch: string,
	release: string,
	hostname: string,
	runtime: string,
	runtime_version: string,
	node_version: string | null,
};

export type ProbeResult = "Ok" | "Fail";

export type RpcErr = {
	name: "RpcErr",
	code: string,
	message: string,
	data: unknown | null,
};

export type RunInfo = {
	asr: AsrRunInfo | null,
};

export type ServerInfo = {
	host: string,
	port: number,
	found_via: FoundVia,
};

/**  Server type identifiers for mDNS discovery. */
export type ServerType = "VoxcpmTorchGradio" | "DemucsTorchServer";

export type Task = {
	id: string,
	source: VideoSource,
	url: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	task_dir: string,
	final_video_path: string | null,
	error_message: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
};

export type TaskBrief = {
	id: string,
	title: string | null,
	status: string,
	current_stage: string | null,
	created_at: string,
	started_at: string | null,
	completed_at: string | null,
	error_message: string | null,
};

export type TaskStage = {
	name: string,
	label: string,
	status: string,
	progress: number | null,
	started_at: string | null,
	completed_at: string | null,
	last_message: string | null,
	error_message: string | null,
};

export type Vendor = "Amd" | "Nvidia" | "Intel" | "Unknown";

export type VideoSource = "Youtube" | "Bilibili" | "Local" | "Remote" | "Unknown";

export type VramInfo = {
	percent: number | null,
	total: number | null,
	used: number | null,
	type: VramType | null,
	reserved: number | null,
	gtt: number | null,
};

export type VramType = "Dedicated" | "Shared" | "Unknown";

export type VulkanHeaps = {
	device_local: number | null,
	host_visible: number | null,
};
export type Procedures = {
  device_info: { kind: "query"; input: null; output: DeviceInfo; error: RpcErr };
  find_server: { kind: "query"; input: ServerType; output: ServerInfo; error: RpcErr };
  get_group_list: { kind: "query"; input: null; output: GroupInfo[]; error: RpcErr };
  get_task_ctx: { kind: "query"; input: string; output: Context; error: RpcErr };
  list_app_directory: { kind: "query"; input: string; output: DirEntry[]; error: RpcErr };
  read_app_file_bin: { kind: "query"; input: string; output: number[]; error: RpcErr };
  read_app_file_text: { kind: "query"; input: string; output: string; error: RpcErr };
  reset_count: { kind: "mutate"; input: null; output: null; error: RpcErr };
  write_app_file_text: { kind: "mutate"; input: [string, string]; output: null; error: RpcErr };
  watch_task_log: { kind: "subscribe"; input: string; output: string; error: RpcErr };
}

export const __procedureKinds = {
  device_info: "query",
  find_server: "query",
  get_group_list: "query",
  get_task_ctx: "query",
  list_app_directory: "query",
  read_app_file_bin: "query",
  read_app_file_text: "query",
  reset_count: "mutate",
  write_app_file_text: "mutate",
  watch_task_log: "subscribe",
} as const;
