// Auto-generated by fnrpc. DO NOT EDIT.

export type GreetInput = { name: string }
export type GreetOutput = { message: string }
export interface RpcRouter {
  greet: { input: GreetInput; output: GreetOutput };
}

export function createRpcClient(opts: { url?: string; invoke?: (method: string, args: Record<string, unknown>) => Promise<unknown> }) {
  async function request<TInput, TOutput>(method: string, input: TInput): Promise<TOutput> {
    if (opts.invoke) {
      return (await opts.invoke('rpc', { method, input })) as TOutput;
    }
    const base = opts.url ?? 'http://localhost:19110/fnrpc';
    const res = await fetch(`${base}/${method}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(input),
    });
    return res.json();
  }

  function createQuery<TInput, TOutput>(fn: () => [string, TInput]) {
    return {
      queryKey: fn,
      queryFn: async () => {
        const [method, input] = fn();
        return request<TInput, TOutput>(method, input);
      },
    };
  }

  function createMutation<TInput, TOutput>(method: string) {
    return {
      mutationFn: (input: TInput) => request<TInput, TOutput>(method, input),
    };
  }

  return {
    request,
    createQuery,
    createMutation,
    Greet: createQuery<GreetInput, GreetOutput>,
  };
}
