// Auto-generated by fnrpc. DO NOT EDIT.

export type GreetInput = { name: string }
export type GreetOutput = { message: string }
export type Procedures = {
  greet: { kind: "query"; input: GreetInput; output: GreetOutput; error: unknown };
}
