// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type ProceduresLegacy = { queries: { key: "checkTorch"; input: null; result: boolean } | { key: "deviceInfo"; input: null; result: string } | { key: "getGroupList"; input: null; result: string } | { key: "readInput"; input: null; result: string } | { key: "readInputSchema"; input: null; result: string } | { key: "version"; input: null; result: string }; mutations: { key: "startTorch"; input: null; result: number } | { key: "startVoxcpm"; input: null; result: number } | { key: "stopTorch"; input: null; result: null } | { key: "stopVoxcpm"; input: null; result: null } | { key: "writeInput"; input: string; result: null }; subscriptions: never }

export type Procedures = {
	checkTorch: { kind: "query", input: null, output: boolean, error: unknown },
	deviceInfo: { kind: "query", input: null, output: string, error: unknown },
	getGroupList: { kind: "query", input: null, output: string, error: unknown },
	readInput: { kind: "query", input: null, output: string, error: unknown },
	readInputSchema: { kind: "query", input: null, output: string, error: unknown },
	startTorch: { kind: "mutation", input: null, output: number, error: unknown },
	startVoxcpm: { kind: "mutation", input: null, output: number, error: unknown },
	stopTorch: { kind: "mutation", input: null, output: null, error: unknown },
	stopVoxcpm: { kind: "mutation", input: null, output: null, error: unknown },
	version: { kind: "query", input: null, output: string, error: unknown },
	writeInput: { kind: "mutation", input: string, output: null, error: unknown },
}