use std::collections::HashMap;
use std::path::Path;

use serde_json::Value;

use crate::error::RpcErr;
use crate::handler::ErasedHandler;

pub struct RpcRouter<Ctx> {
    handlers: HashMap<&'static str, Box<dyn ErasedHandler<Ctx>>>,
}

impl<Ctx> RpcRouter<Ctx>
where
    Ctx: Send + Sync + 'static,
{
    pub fn new() -> Self {
        Self {
            handlers: HashMap::new(),
        }
    }

    pub fn add<H: ErasedHandler<Ctx> + 'static>(&mut self, handler: H) -> &mut Self {
        let name = handler.name();
        self.handlers.insert(name, Box::new(handler));
        self
    }

    pub async fn dispatch(
        &self,
        ctx: &Ctx,
        method: &str,
        input: Value,
    ) -> Result<Value, RpcErr> {
        let handler = self
            .handlers
            .get(method)
            .ok_or_else(|| RpcErr(format!("unknown method: {method}")))?;
        handler.call(ctx, input).await
    }

    /// Export all registered types as TypeScript type definitions.
    pub fn export_ts(&self) -> HashMap<&'static str, String> {
        let mut map = HashMap::new();
        for (name, handler) in &self.handlers {
            map.insert(*name, handler.export_ts());
        }
        map
    }

    /// Generate TypeScript type definitions and a Procedures interface.
    pub fn generate_ts_client(&self, _rpc_url: &str) -> String {
        let mut out = String::new();

        out.push_str("// Auto-generated by fnrpc. DO NOT EDIT.\n\n");

        // Type definitions from specta
        for (_name, handler) in &self.handlers {
            out.push_str(&handler.export_ts());
            out.push('\n');
        }

        // Procedures type definition (rspc-next compatible)
        out.push_str("export type Procedures = {\n");
        for (_, handler) in &self.handlers {
            let i = handler.input_type_name();
            let o = handler.output_type_name();
            let kind = handler.kind();
            out.push_str(&format!(
                "  {}: {{ kind: \"{kind}\"; input: {i}; output: {o}; error: unknown }};\n",
                handler.name()
            ));
        }
        out.push_str("}\n");

        out
    }

    /// Generate and write a TypeScript client file to disk.
    pub fn write_ts_client(&self, rpc_url: &str, output_path: &Path) -> std::io::Result<()> {
        let content = self.generate_ts_client(rpc_url);
        std::fs::write(output_path, content)
    }
}


