use std::collections::HashMap;
use std::path::Path;

use serde_json::Value;

use crate::error::RpcErr;
use crate::handler::ErasedHandler;

pub struct RpcRouter<Ctx> {
    handlers: HashMap<&'static str, Box<dyn ErasedHandler<Ctx>>>,
}

impl<Ctx> RpcRouter<Ctx>
where
    Ctx: Send + Sync + 'static,
{
    pub fn new() -> Self {
        Self {
            handlers: HashMap::new(),
        }
    }

    pub fn add<H: ErasedHandler<Ctx> + 'static>(&mut self, handler: H) -> &mut Self {
        let name = handler.name();
        self.handlers.insert(name, Box::new(handler));
        self
    }

    pub async fn dispatch(
        &self,
        ctx: &Ctx,
        method: &str,
        input: Value,
    ) -> Result<Value, RpcErr> {
        let handler = self
            .handlers
            .get(method)
            .ok_or_else(|| RpcErr(format!("unknown method: {method}")))?;
        handler.call(ctx, input).await
    }

    /// Export all registered types as TypeScript type definitions.
    pub fn export_ts(&self) -> HashMap<&'static str, String> {
        let mut map = HashMap::new();
        for (name, handler) in &self.handlers {
            map.insert(*name, handler.export_ts());
        }
        map
    }

    /// Generate a TypeScript client file for all registered procedures.
    pub fn generate_ts_client(&self, rpc_url: &str) -> String {
        let mut out = String::new();

        out.push_str("// Auto-generated by fnrpc. DO NOT EDIT.\n\n");

        // Type definitions from specta
        for (_name, handler) in &self.handlers {
            out.push_str(&handler.export_ts());
            out.push('\n');
        }

        // Client
        out.push_str("export interface RpcRouter {\n");
        for (_, handler) in &self.handlers {
            let i = handler.input_type_name();
            let o = handler.output_type_name();
            out.push_str(&format!("  {name}: {{ input: {i}; output: {o} }};\n",
                name = handler.name()));
        }
        out.push_str("}\n\n");

        out.push_str("export function createRpcClient(opts: { url?: string; invoke?: (method: string, args: Record<string, unknown>) => Promise<unknown> }) {\n");
        out.push_str("  async function request<TInput, TOutput>(method: string, input: TInput): Promise<TOutput> {\n");
        out.push_str("    if (opts.invoke) {\n");
        out.push_str("      return (await opts.invoke('rpc', { method, input })) as TOutput;\n");
        out.push_str("    }\n");
        out.push_str(&format!("    const base = opts.url ?? '{}';\n", rpc_url));
        out.push_str("    const res = await fetch(`${base}/${method}`, {\n");
        out.push_str("      method: 'POST',\n");
        out.push_str("      headers: { 'Content-Type': 'application/json' },\n");
        out.push_str("      body: JSON.stringify(input),\n");
        out.push_str("    });\n");
        out.push_str("    return res.json();\n");
        out.push_str("  }\n\n");

        out.push_str("  function createQuery<TInput, TOutput>(fn: () => [string, TInput]) {\n");
        out.push_str("    return {\n");
        out.push_str("      queryKey: fn,\n");
        out.push_str("      queryFn: async () => {\n");
        out.push_str("        const [method, input] = fn();\n");
        out.push_str("        return request<TInput, TOutput>(method, input);\n");
        out.push_str("      },\n");
        out.push_str("    };\n");
        out.push_str("  }\n\n");

        out.push_str("  function createMutation<TInput, TOutput>(method: string) {\n");
        out.push_str("    return {\n");
        out.push_str("      mutationFn: (input: TInput) => request<TInput, TOutput>(method, input),\n");
        out.push_str("    };\n");
        out.push_str("  }\n\n");

        out.push_str("  return {\n");
        out.push_str("    request,\n");
        out.push_str("    createQuery,\n");
        out.push_str("    createMutation,\n");
        for (_, handler) in &self.handlers {
            let camel = snake_to_camel(&handler.name());
            let i = handler.input_type_name();
            let o = handler.output_type_name();
            out.push_str(&format!("    {camel}: createQuery<{i}, {o}>,\n"));
        }
        out.push_str("  };\n");
        out.push_str("}\n");

        out
    }

    /// Generate and write a TypeScript client file to disk.
    pub fn write_ts_client(&self, rpc_url: &str, output_path: &Path) -> std::io::Result<()> {
        let content = self.generate_ts_client(rpc_url);
        std::fs::write(output_path, content)
    }
}

fn snake_to_camel(s: &str) -> String {
    let mut out = String::new();
    for part in s.split('_') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    out
}
