use std::collections::HashMap;
use std::path::Path;
use std::pin::Pin;
use std::sync::Arc;

use futures::stream::Stream;
use serde_json::Value;
use specta::TypeCollection;
use specta_typescript::Typescript;

use crate::error::RpcErr;
use crate::handler::{ErasedHandler, ErasedSubscriptionHandler};
use crate::middleware::{FnLayer, FnService};

pub struct RpcRouter<Ctx> {
    inner: Arc<RpcRouterInner<Ctx>>,
}

struct RpcRouterInner<Ctx> {
    handlers: HashMap<&'static str, Arc<dyn ErasedHandler<Ctx>>>,
    subscriptions: HashMap<&'static str, Arc<dyn ErasedSubscriptionHandler<Ctx>>>,
    layers: Vec<Box<dyn FnLayer<Ctx>>>,
}

impl<Ctx> Clone for RpcRouter<Ctx> {
    fn clone(&self) -> Self {
        Self { inner: self.inner.clone() }
    }
}

impl<Ctx> RpcRouter<Ctx>
where
    Ctx: Send + Sync + 'static,
{
    pub fn new() -> Self {
        Self {
            inner: Arc::new(RpcRouterInner {
                handlers: HashMap::new(),
                subscriptions: HashMap::new(),
                layers: Vec::new(),
            }),
        }
    }

    pub fn route<H: ErasedHandler<Ctx> + 'static>(self, handler: H) -> Self {
        let name = handler.name();
        let mut inner = Arc::try_unwrap(self.inner)
            .unwrap_or_else(|_| unreachable!("consumed self => sole owner"));
        inner.handlers.insert(name, Arc::new(handler));
        Self { inner: Arc::new(inner) }
    }

    /// Register a subscription handler.
    pub fn subscribe<H: ErasedSubscriptionHandler<Ctx> + 'static>(self, handler: H) -> Self {
        let name = handler.name();
        let mut inner = Arc::try_unwrap(self.inner)
            .unwrap_or_else(|_| unreachable!("consumed self => sole owner"));
        inner.subscriptions.insert(name, Arc::new(handler));
        Self { inner: Arc::new(inner) }
    }

    /// Attach a middleware layer.
    ///
    /// Similar to Hono's `.use()`, TanStack Start's `.middleware()`,
    /// or Tower's `.layer()`. The last call becomes the outermost layer.
    pub fn layer<L: FnLayer<Ctx> + 'static>(self, layer: L) -> Self {
        let mut inner = Arc::try_unwrap(self.inner)
            .unwrap_or_else(|_| unreachable!("consumed self => sole owner"));
        inner.layers.push(Box::new(layer));
        Self { inner: Arc::new(inner) }
    }

    pub async fn dispatch(
        &self,
        ctx: &Ctx,
        path: &str,
        input: Value,
    ) -> Result<Value, RpcErr> {
        let mut svc: Box<dyn FnService<Ctx>> = Box::new(RouterService {
            handlers: self.inner.handlers.clone(),
        });
        for layer in self.inner.layers.iter() {
            svc = layer.layer(svc);
        }
        svc.call(ctx, path, input).await
    }

    /// Dispatch a subscription by path, returning a stream of values.
    pub fn dispatch_subscribe(
        &self,
        ctx: &Ctx,
        path: &str,
        input: Value,
    ) -> Result<Pin<Box<dyn Stream<Item = Result<Value, RpcErr>> + Send>>, RpcErr> {
        let handler = self
            .inner
            .subscriptions
            .get(path)
            .ok_or_else(|| RpcErr(format!("unknown subscription path: {path}")))?;
        Ok(handler.call(ctx, input))
    }

    /// Generate TypeScript type definitions and a Procedures interface.
    pub fn generate_ts_client(&self, _rpc_url: &str) -> String {
        use std::collections::HashSet;

        use specta::datatype::DataType;

        // Collect types: shared TypeCollection (transitive deps) + top-level DataTypes
        let mut type_map = TypeCollection::default();
        let mut top_level: Vec<DataType> = Vec::new();
        for (_, handler) in &self.inner.handlers {
            handler.populate_types(&mut type_map, &mut top_level);
        }
        for (_, sub) in &self.inner.subscriptions {
            sub.populate_types(&mut type_map, &mut top_level);
        }

        // Export all types from the shared TypeCollection (transitive deps)
        let typescript = Typescript::new()
            .framework_header("// Auto-generated by fnrpc. DO NOT EDIT.");
        let mut out = typescript.export(&type_map).unwrap_or_default();
        if !out.is_empty() && !out.ends_with('\n') {
            out.push('\n');
        }

        // Export top-level handler input/output types (de-duplicated by name)
        let mut seen: HashSet<String> = HashSet::new();
        for dt in &top_level {
            let name = match dt {
                DataType::Struct(s) => Some(s.name().to_string()),
                DataType::Enum(e) => Some(e.name().to_string()),
                _ => None,
            };
            if let Some(name) = name {
                if seen.insert(name.clone()) {
                    let named = dt.clone().to_named(name);
                    if let Ok(export) =
                        specta_typescript::export_named_datatype(
                            &typescript, &named, &type_map,
                        )
                    {
                        out.push_str(&export);
                        out.push_str("\n\n");
                    }
                }
            }
        }

        out.push_str("export type Procedures = {\n");
        for (_, handler) in &self.inner.handlers {
            let i = handler.input_ts();
            let o = handler.output_ts();
            let kind = handler.kind();
            out.push_str(&format!(
                "  {}: {{ kind: \"{kind}\"; input: {}; output: {}; error: unknown }};\n",
                handler.name(),
                i.ts_ref,
                o.ts_ref,
            ));
        }
        for (_, sub) in &self.inner.subscriptions {
            let i = sub.input_ts();
            let o = sub.output_ts();
            out.push_str(&format!(
                "  {}: {{ kind: \"subscription\"; input: {}; output: {}; error: unknown }};\n",
                sub.name(),
                i.ts_ref,
                o.ts_ref,
            ));
        }
        out.push_str("}\n");

        out
    }

    /// Generate and write a TypeScript client file to disk.
    pub fn write_ts_client(&self, rpc_url: &str, output_path: &Path) -> std::io::Result<()> {
        let content = self.generate_ts_client(rpc_url);
        std::fs::write(output_path, content)
    }
}

/// Inner service that dispatches to handlers directly.
struct RouterService<Ctx> {
    handlers: HashMap<&'static str, Arc<dyn ErasedHandler<Ctx>>>,
}

#[async_trait::async_trait]
impl<Ctx: Send + Sync + 'static> FnService<Ctx> for RouterService<Ctx> {
    async fn call(&self, ctx: &Ctx, path: &str, input: Value) -> Result<Value, RpcErr> {
        let handler = self
            .handlers
            .get(path)
            .ok_or_else(|| RpcErr(format!("unknown path: {path}")))?;
        handler.call(ctx, input).await
    }
}
